language: minimal

services:
- docker

install:
- docker build . -t release-image

before_deploy:
- docker create --name release release-image
- docker cp release:/var/artifacts artifacts

deploy:
- provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: artifacts/gh-pages
  on:
    branch: feat-restructure
  skip_cleanup: true
